import type { Metadata } from "next";
import { inter } from "@/app/ui/fonts";
import "./globals.css";
import QueryClientProvider from "./providers/TanstackReactQuery/index";
import ResponsiveProvider from "./providers/Responsive";
import NextUIProvider from "./providers/NextUi/NextUIProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: 'rgb(30 41 59)' }}>
      <head>
      </head>
      <body className={`${inter.className} antialiased bg-slate-800`}>
        <NextUIProvider>
          <QueryClientProvider>
            <ResponsiveProvider>
              {children}
            </ResponsiveProvider>
         </QueryClientProvider>
        </NextUIProvider>
      </body>
      </html>
  )
}
